### ISSUE TITLE
mbedtls support for MBEDTLS_NET_C needs to be documented 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1996]
#1889 introduced the `MBEDTLS_NET_C` into the default mbedtls/config.h v0.6 ships with, but there's no documentation of this or how to use it. A couple of issues:

- [x] Comment in config.h needs to be updated, currently still says:
    `// Open Enclave: disabled, network I/O is currently unsupported in enclaves`
- [x] [MbedtlsSupport.md](https://github.com/openenclave/openenclave/blob/master/docs/MbedtlsSupport.md) function support has not been updated to cover enabled ssl*.h features. 
- [x] Some notification on how to actually enable the features (linking to Mike's doc on enabling file I/O & sockets) is needed, in particular noting that while mbedtls will build and link just fine, the expanded set of APIs that depend on `MBEDTLS_NET_C` will fail at runtime unless correctly linked to the optional device libraries. 

Related to #1893.

Attn: @soccerGB, @gupta-ak, @radhikaj

**Comment by anitagov** [comment]
#1943 opened by me already addresses your second bullet.

We also need to reiterate that although File I/O is supported in enclaves, MBEDTLS_FS_IO is not enabled for Release 0.6.

Also good to mention the reasoning behind oe_syscall not being used in the mbed test for Release 0.6.

**Comment by yakman2020** [comment]
Fixed by #1943 #1975 #1999 and #1994

**Comment by anitagov** [comment]
Updated comment from @yakman2020 to remove #1975 as that is not fixed for Release 0.6 but will be done for 0.7
